### ISSUE TITLE
Docker install

### ISSUE THREAD

**Issue by Eirikr70** [kekePower/cognito-ai-search#5]
Hello, thanks for sharing your work !

I can't have any success in having Cognito to run. I get the following screen.

![Image](https://github.com/user-attachments/assets/6090639d-c462-4f86-ab5b-6073165500ad)

I have set up the following `docker-compose.yml`

```
services:
  cognito:
    build: .
    container_name: cognito
    env_file:
      - .env
    restart: on-failure:5
    ports:
      - 3000:3000
    cpus: "2.0"
    cpu_shares: 256
    networks:
      - cognito

  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    restart: on-failure:5
    ports:
      - 8888:8080
    volumes:
      - ./searxng:/etc/searxng:rw
    env_file:
      - .env
    networks:
      - cognito

  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    restart: on-failure:5
    env_file:
      - .env
    cpus: "2.0"
    cpu_shares: 256
    networks:
      - cognito

networks:
  cognito:
```
With the following `.env` file
```
# Ollama Configuration
OLLAMA_API_URL=http://127.0.0.1:11434
DEFAULT_OLLAMA_MODEL=phi4-mini:3.8b-q8_0
AI_RESPONSE_MAX_TOKENS=100

# SearXNG Configuration
SEARXNG_API_URL=http://127.0.0.1:8888
SEARXNG_BASE_URL=http://127.0.0.1:8888
# SEARXNG_HOSTNAME=<host>
UWSGI_WORKERS=4
UWSGI_THREADS=4

# Client-side environment variables (prefixed with NEXT_PUBLIC_)
NEXT_PUBLIC_OLLAMA_API_URL=${OLLAMA_API_URL}
NEXT_PUBLIC_SEARXNG_API_URL=${SEARXNG_API_URL}
NEXT_PUBLIC_DEFAULT_OLLAMA_MODEL=${DEFAULT_OLLAMA_MODEL}

# Next.js Configuration
NEXT_PUBLIC_APP_URL=http://127.0.0.1:3000

TZ="Europe/Paris"
```
The SearXNG container is functional, port 11434 answers "Ollama is running". The logs for Cognito are as follows
```
   ▲ Next.js 15.3.2
   - Local:        http://7cbc15fee631:3000
   - Network:      http://7cbc15fee631:3000

 ✓ Starting...
 ✓ Ready in 119ms
```
Got any clue ?
